version: '3'

services:
    db:
        image: postgres
    apache:
        image: ssl-api-apache
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/code
        depends_on:
            - db
